"""Add knowledge quality score fields

Revision ID: 3820573ead02
Revises: 4430c04687c2
Create Date: 2026-07-22 23:39:58.112483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3820573ead02'
down_revision: Union[str, Sequence[str], None] = '4430c04687c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('quality_level', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'quality_level')
    op.drop_column('documents', 'quality_score')
    # ### end Alembic commands ###
