"""Add user foreign key to search queries

Revision ID: 58f82011e43c
Revises: 91bfc2fe367a
Create Date: 2026-08-23 22:39:49.893751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f82011e43c'
down_revision: Union[str, Sequence[str], None] = '91bfc2fe367a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('answer', sa.Text(), nullable=True))
    op.alter_column('search_queries', 'query',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('search_queries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_search_queries_searched_at'), 'search_queries', ['searched_at'], unique=False)
    op.drop_constraint(op.f('search_queries_user_id_fkey'), 'search_queries', type_='foreignkey')
    op.create_foreign_key(None, 'search_queries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_queries', type_='foreignkey')
    op.create_foreign_key(op.f('search_queries_user_id_fkey'), 'search_queries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_search_queries_searched_at'), table_name='search_queries')
    op.alter_column('search_queries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_queries', 'query',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('search_queries', 'answer')
    # ### end Alembic commands ###
