"""Add document classification fields

Revision ID: 665cf327ecf2
Revises: 66fbf42195f4
Create Date: 2026-07-21 23:29:09.895430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665cf327ecf2'
down_revision: Union[str, Sequence[str], None] = '66fbf42195f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'category')
    # ### end Alembic commands ###
