"""add search analytics fields

Revision ID: 91bfc2fe367a
Revises: 499f20c520e2
Create Date: 2026-08-13 13:34:10.450710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bfc2fe367a'
down_revision: Union[str, Sequence[str], None] = '499f20c520e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('search_time', sa.Float(), nullable=True))
    op.add_column('search_queries', sa.Column('llm_time', sa.Float(), nullable=True))
    op.add_column('search_queries', sa.Column('total_rag_time', sa.Float(), nullable=True))
    op.add_column('search_queries', sa.Column('was_answered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'was_answered')
    op.drop_column('search_queries', 'total_rag_time')
    op.drop_column('search_queries', 'llm_time')
    op.drop_column('search_queries', 'search_time')
    # ### end Alembic commands ###
